### ISSUE TITLE
Issue running against terraform 0.9.2

### ISSUE THREAD

**Issue by wingZero21** [HewlettPackard/terraform-provider-oneview#27]
Hi,

I am getting the below error when running against the latest terraform version. Is there anything that needs to be amended for this to work?

```* provider.oneview: Incompatible API version with plugin. Plugin version: 3, Ours: 4```

**Comment by patrickdappollonio** [comment]
Hello @wingZero21,

The current terraform provider is built against the release branch 0.8.x, so 0.9.2 is not compatible looks like.

I'll update our code as soon as possible to benefit from 0.9.2 niceties.

**Comment by patrickdappollonio** [comment]
Hello @wingZero21,

@dh2mom247 just merged the PR that fixes this issue. `terraform-provider-oneview` now supports 0.9.2.

Try it and let us know!

**Comment by wingZero21** [comment]
Hi,

Thanks for the update. I tried re-adding this however I get the below error. Any ideas what might be causing it?

Details:
```../go/src/github.com/HewlettPackard/terraform-provider-oneview/vendor/github.com/hashicorp/terraform/terraform/context.go:682: undefined: sort.Slice```

**Comment by wingZero21** [comment]
Hi,

I was running the below go version when that error occurred.

I have since updated to 1.8 and its stopped the error from occuring.

Cheers

Details:
```go version go1.7.5 darwin/amd64```

Working go version
```go version go1.8 darwin/amd64```
